# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: yara-normalize 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "yara-normalize".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["chrislee35".freeze]
  s.date = "2022-05-01"
  s.description = "To enable consistent comparisons between yara rules (signature), a uniform hashing standard was needed.".freeze
  s.email = "rubygems@chrislee.dhs.org".freeze
  s.executables = ["yaratool".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/yaratool",
    "lib/yara-normalize.rb",
    "lib/yara-normalize/yara-normalize.rb",
    "test/helper.rb",
    "test/test_yara-normalize.rb",
    "yara-normalize.gemspec"
  ]
  s.homepage = "http://github.com/chrislee35/yara-normalize".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.2.3".freeze
  s.summary = "Normalizes Yara Signatures into a repeatable hash even when non-transforming changes are made".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<shoulda>.freeze, [">= 4"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.4"])
    s.add_development_dependency(%q<bundler>.freeze, ["~> 2.3"])
    s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    s.add_development_dependency(%q<test-unit>.freeze, ["~> 3.5.3"])
  else
    s.add_dependency(%q<shoulda>.freeze, [">= 4"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 6.4"])
    s.add_dependency(%q<bundler>.freeze, ["~> 2.3"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    s.add_dependency(%q<test-unit>.freeze, ["~> 3.5.3"])
  end
end

